# Î¼VERSE configuration in YAML format
defaultBump: patch

commitTypes:
  feat: minor
  fix: patch
  perf: patch
  refactor: patch
  docs: ignore
  test: ignore
  chore: ignore
  style: ignore
  ci: ignore
  build: ignore
  breaking: major

dependencyRules:
  onMajorOfDependency: minor
  onMinorOfDependency: patch
  onPatchOfDependency: none

nodejs:
  versionSource:
    - package.json
  updatePackageLock: true