name: 'VERSE - Version Engine for Repo Semantic Evolution'
description: 'Intelligent semantic version management engine for monorepo projects with dependency cascade evolution'
author: 'Your Organization'
inputs:
  dry-run:
    description: 'Run without writing or pushing'
    required: false
    default: 'false'
  adapter:
    description: 'Language adapter (e.g., gradle). Auto-detected if not provided'
    required: false
    default: ''
  push-tags:
    description: 'Push tags to origin'
    required: false
    default: 'true'
  prerelease-mode:
    description: 'Generate pre-release versions instead of final versions'
    required: false
    default: 'false'
  prerelease-id:
    description: 'Pre-release identifier (e.g., alpha, beta, rc)'
    required: false
    default: 'alpha'
  bump-unchanged:
    description: 'In prerelease mode, bump modules even when no changes are detected'
    required: false
    default: 'false'
  add-build-metadata:
    description: 'Add build metadata with short SHA to all versions'
    required: false
    default: 'false'
  timestamp-versions:
    description: 'Use timestamp-based prerelease identifiers (requires prerelease-mode)'
    required: false
    default: 'false'
  append-snapshot:
    description: 'Add -SNAPSHOT suffix to all versions if supported by adapter'
    required: false
    default: 'false'
  push-changes:
    description: 'Commit and push version changes and changelogs to remote'
    required: false
    default: 'true'
  generate-changelog:
    description: 'Generate or update changelog files for changed modules'
    required: false
    default: 'true'
outputs:
  bumped:
    description: 'Whether any module was bumped'
  changed-modules:
    description: 'JSON array of { name, from, to }'
  created-tags:
    description: 'List of created tags'
  changelog-paths:
    description: 'Generated changelog files'
runs:
  using: 'node20'
  main: 'packages/action/dist/index.js'